Feature/itrex 357
IT-REX-Platform/MediaService pull request #10
Opened 2021-01-27 15:20 UTC by GarondEisenfaust

Hab das bestehende etwas umgeschrieben, damit es einfacher testbar und einfacher zu verwenden ist. Hab ein Paar Code Beispiel gefunden bei denen in jeder Interaktion mit Minio einen neuen Client erstellt wird https://www.programcreek.com/java-api-examples/?api=io.minio.MinioClient. Hab das auch so übernommen. Und Test natürlich.

2021-01-27 15:22 UTC, GarondEisenfaust commented
Und die sonar pfade passen jetzt auch

2021-01-27 15:37 UTC, Noeliel approved these changes

2021-01-27 15:37 UTC, Noeliel commented on src/test/resources/docker/minio.yml
> +    image: "minio/minio:RELEASE.2021-01-16T02-19-44Z"
Benutzen wir absichtlich diese ultra spezifische Version?

2021-01-27 15:41 UTC, GarondEisenfaust commented on src/test/resources/docker/minio.yml
> +    image: "minio/minio:RELEASE.2021-01-16T02-19-44Z"
Ist die letzte Version. hab mir gedacht man gibt die lieber spezifisch an bevor ne spätere Version breaking changes hat. Also ja das war Absicht.

2021-01-27 16:06 UTC, GarondEisenfaust commented on src/test/resources/docker/minio.yml
> +    image: "minio/minio:RELEASE.2021-01-16T02-19-44Z"
Es lässt sich aber bestimmt auch eine finden die angenehmer zu lesen ist

2021-01-27 18:27 UTC, Well5a requested changes
Gibt es einen Grund wieso wir jetzt schon mergen? Super Arbeit Christian, es fehlen halt noch andere Features

2021-01-27 18:39 UTC, GarondEisenfaust commented
Damit man einfach daran weiterarbeiten kann

2021-01-27 18:52 UTC, Well5a requested changes
Gibt es einen Grund wieso wir jetzt schon mergen? Es fehlen halt noch ein paar grundlegende Features für das Ticket.
Ansonsten super Arbeit Christian!

2021-01-27 18:52 UTC, Well5a commented on src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +      "description": "Description for minio.access-key."
Sollten wir die Beschreibung hier ändern?

2021-01-27 18:52 UTC, Well5a commented on src/main/resources/config/application.yml
> +minio:
Good change!

2021-01-27 18:52 UTC, Well5a commented on src/test/resources/docker/minio.yml
> +    image: "minio/minio:RELEASE.2021-01-16T02-19-44Z"
Hab grade mal nachgeschaut ich glaube die heißen alle so

2021-01-27 18:52 UTC, Well5a commented on src/main/java/de/uni_stuttgart/it_rex/media/written/video/VideoStorageService.java
> +    public final String getAccessKey() {
Benötigen wir die getter Methoden und falls ja, müssen die public sein? Wäre glaube ich besser wenn die zumindest private wären. 
Und noch ne andere Frage einfach aus Interesse: Gibt es einen Grund, weshalb du die Properties mit settern und nicht mit dem Konstruktor initialisierst?

2021-01-27 18:56 UTC, Well5a commented
> Damit man einfach daran weiterarbeiten kann

Brauchen das andere User Stories? Von mir aus können wir es dann auch so mergen

2021-01-28 15:05 UTC, Noeliel commented on src/test/resources/docker/minio.yml
> +    image: "minio/minio:RELEASE.2021-01-16T02-19-44Z"
> Ist die letzte Version. hab mir gedacht man gibt die lieber spezifisch an bevor ne spätere Version breaking changes hat. Also ja das war Absicht.

Klingt sinnvoll.

2021-01-28 15:08 UTC, Noeliel commented
> Gibt es einen Grund wieso wir jetzt schon mergen? Super Arbeit Christian, es fehlen halt noch andere Features

Also ich hab mein Feature Branch einfach auf eurem basiert und das bisher einmal rebased/upgedated. Dann hab ich immer euren Stand der Dinge mehr oder weniger aktuell und kann meinen Kram parallel dazu bauen. Soll heißen, wegen mir muss es jetzt noch nicht unbedingt gemerged werden.

2021-01-28 15:34 UTC, Noeliel commented on src/main/resources/config/application.yml
> +  url: http://minio_test:${minio.port}
minio_test statt minio?

2021-01-28 15:52 UTC, GarondEisenfaust commented on src/main/java/de/uni_stuttgart/it_rex/media/written/video/VideoStorageService.java
> +    public final String getAccessKey() {
Ja sonst kann man den setter nicht testen und man muss den testen sonst ist die coverage auf Dauer zu niedrig.

Ich mach das deswegen so weils dadurch einfacher damit ist die Sachen im nachhinein zu ändern (auch im Hinblick auf tests, manche Sachen sind erst bekannt sobald ein Container gestartet ist).

2021-01-28 15:52 UTC, GarondEisenfaust commented on src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +      "description": "Description for minio.access-key."
Ich hab keinen Dunst ich seh das zum ersten mal

2021-01-28 15:57 UTC, GarondEisenfaust commented on src/main/resources/config/application.yml
> +  url: http://minio_test:${minio.port}
True da hab ich wohl das falsche file geändert. Ich pass das an.

2021-01-28 16:27 UTC, GarondEisenfaust commented
Unter den Bedingungen schließ ich den einfach und schieb meine Änderungen von dem 357-cont branch auf diesen

2021-01-28 16:35 UTC, GarondEisenfaust commented
Also wenns für euch okay ist?

2021-01-29 14:09 UTC, closed without merging