Implementation of possible development JHipster strategy
IT-REX-Platform/MediaService pull request #12
Opened 2021-01-31 11:17 UTC by GarondEisenfaust

I implemented the strategy from https://youtu.be/9WVpwIUEty0?t=1000 (timestamp when he starts speaking about the relevant stuff) as an example in this service. I think this might be a viable way for us to continue developing in the future. It allows us to use to utilize the code that was generated by JHipster and add our own without losing it when regenerating our services. Config files are still overwritten unfortunately.

2021-01-31 13:20 UTC, Well5a requested changes
Umbenennung in ...Extended finde ich sehr gut! Allgemein gefällt mir der Ansatz sehr gut.

Benötigen wir die example video file src/main/resources/2_5435963561916500351.mp4 ?

Wir haben jetzt auch 2 postman collections abgelegt. Ich habe eine angelegt in src/test/resources/MediaService.postman_collection.json und du in src/main/resources/postman/http-requests.json . Deine ist besser aber macht vlt im testpackage mehr Sinn? Ich denke es wäre gut wenn wir sie nach dem mediaservice benennen denn wenn wir collections aus verschiedenen services is postman importiert verliert man schnell den Überblick.

2021-01-31 13:20 UTC, Well5a commented on src/main/java/de/uni_stuttgart/it_rex/media/written/video/VideoServiceExtended.java
> +     * Store a video file from the system.
Delete? ;)

2021-01-31 13:20 UTC, Well5a commented on src/main/java/de/uni_stuttgart/it_rex/media/written/video/VideoServiceExtended.java
> +    private PlatformTransactionManager transactionManager;
JavaDoc missing?

2021-01-31 13:20 UTC, Well5a commented on src/main/java/de/uni_stuttgart/it_rex/media/written/video/VideoServiceExtended.java
> +     * Getter.
move getter and setter to bottom?

2021-01-31 14:01 UTC, GarondEisenfaust commented on src/main/java/de/uni_stuttgart/it_rex/media/written/video/VideoServiceExtended.java
> +     * Store a video file from the system.
Ja das Video braucht man für meine postman collection. Mit irgendwas muss man es schließlich testen😁
Jo ich kanns auch noch ins test package verschieben. Mir ists egal:D

Und natürlich ups🤣

Ich kümmer mich spätestens morgen drum😁

2021-01-31 14:01 UTC, GarondEisenfaust commented on src/main/java/de/uni_stuttgart/it_rex/media/written/video/VideoServiceExtended.java
> +    private PlatformTransactionManager transactionManager;
Hab ich wohl übersehen

2021-01-31 17:04 UTC, GarondEisenfaust reviewed
@Well5a hab alles gefixt🤙🏻

2021-01-31 17:04 UTC, GarondEisenfaust commented on src/main/java/de/uni_stuttgart/it_rex/media/written/video/VideoServiceExtended.java
> +     * Getter.
jup willst du etwa ewig scrollen bis du bei relevantem code ankommst:P

2021-01-31 19:18 UTC, Well5a submitted a review, later dismissed

2021-02-01 11:57 UTC, Well5a approved these changes

2021-02-01 16:44 UTC, merged